# @package _global_

# this config file is used for running the template default tests

defaults:
  - _self_
  - datamodule: mnist # choose datamodule with `test_dataloader()` for evaluation
  - module: mnist
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"
predict: False

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
